# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 05:29
from __future__ import unicode_literals

from django.db import migrations


STATUSES = ["busy", "away", "online", "invisible"]

def combine_statuses(apps, schema_editor):

	# We can't import the Person model directly as it may be a newer
	# version than this migration expects. We use the historical version.
	UserStatus = apps.get_model("management", "UserStatus")

	for utype in STATUSES:
		user_status_model = UserStatus(name=utype)
		user_status_model.save()

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_data_add_types'),
    ]

    operations = [
    	migrations.RunPython(combine_statuses),
    ]
