# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_data_add_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='name'),
        ),
    ]
