# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 06:52
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('management', '0008_auto_20160908_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
