# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 06:54
#
from __future__ import unicode_literals

from django.db import migrations

TYPES = ["admin", "manager", "customer"]

def combine_groups(apps, schema_editor):

	# We can't import the Person model directly as it may be a newer
	# version than this migration expects. We use the historical version.
	UserGroup = apps.get_model("management", "UserGroup")

	for utype in TYPES:
		user_group = UserGroup(name=utype)
		user_group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_usergroup'),
    ]

    operations = [
    	migrations.RunPython(combine_groups),
    ]

